-- Enable UUID extension
create extension if not exists "uuid-ossp";

-- Create updated tasks table with user relationship
create table if not exists tasks (
  id bigint generated by default as identity primary key,
  user_id uuid references auth.users(id) on delete cascade not null,
  created_at timestamp with time zone default timezone('utc'::text, now()) not null,
  updated_at timestamp with time zone default timezone('utc'::text, now()) not null,
  title text not null,
  description text,
  is_completed boolean default false,
  due_date timestamp with time zone,
  priority text default 'medium',
  tags text[] default '{}',
  subtasks jsonb default '[]',
  estimated_time integer, -- in minutes
  actual_time integer, -- in minutes
  status text default 'pending', -- pending, in_progress, completed, archived
  dependencies bigint[], -- array of task IDs
  recurrence jsonb, -- {type: 'daily', interval: 1, end_date: null}
  is_archived boolean default false
);

-- Create analytics table for tracking productivity
create table if not exists task_analytics (
  id bigint generated by default as identity primary key,
  user_id uuid references auth.users(id) on delete cascade not null,
  task_id bigint references tasks(id) on delete cascade,
  completed_at timestamp with time zone,
  time_spent integer, -- in minutes
  created_at timestamp with time zone default timezone('utc'::text, now()) not null
);

-- Create user stats table
create table if not exists user_stats (
  user_id uuid references auth.users(id) on delete cascade primary key,
  total_xp integer default 0,
  level integer default 1,
  tasks_completed integer default 0,
  current_streak integer default 0,
  longest_streak integer default 0,
  achievements text[] default '{}',
  last_activity timestamp with time zone,
  created_at timestamp with time zone default timezone('utc'::text, now()) not null
);

-- Enable Row Level Security
alter table tasks enable row level security;
alter table task_analytics enable row level security;
alter table user_stats enable row level security;

-- RLS Policies for tasks
create policy "Users can view their own tasks"
  on tasks for select
  using (auth.uid() = user_id);

create policy "Users can insert their own tasks"
  on tasks for insert
  with check (auth.uid() = user_id);

create policy "Users can update their own tasks"
  on tasks for update
  using (auth.uid() = user_id);

create policy "Users can delete their own tasks"
  on tasks for delete
  using (auth.uid() = user_id);

-- RLS Policies for task_analytics
create policy "Users can view their own analytics"
  on task_analytics for select
  using (auth.uid() = user_id);

create policy "Users can insert their own analytics"
  on task_analytics for insert
  with check (auth.uid() = user_id);

-- RLS Policies for user_stats
create policy "Users can view their own stats"
  on user_stats for select
  using (auth.uid() = user_id);

create policy "Users can insert their own stats"
  on user_stats for insert
  with check (auth.uid() = user_id);

create policy "Users can update their own stats"
  on user_stats for update
  using (auth.uid() = user_id);

-- Function to auto-create user stats on signup
create or replace function public.handle_new_user()
returns trigger as $$
begin
  insert into public.user_stats (user_id)
  values (new.id);
  return new;
end;
$$ language plpgsql security definer;

-- Trigger to create user stats on new user
drop trigger if exists on_auth_user_created on auth.users;
create trigger on_auth_user_created
  after insert on auth.users
  for each row execute procedure public.handle_new_user();

-- Function to update updated_at timestamp
create or replace function update_updated_at_column()
returns trigger as $$
begin
  new.updated_at = now();
  return new;
end;
$$ language plpgsql;

-- Trigger to auto-update updated_at
drop trigger if exists update_tasks_updated_at on tasks;
create trigger update_tasks_updated_at
  before update on tasks
  for each row execute procedure update_updated_at_column();
