import { useMemo, useState } from 'react';
import { format } from 'date-fns';
import {
  CalendarDays, Hash, Loader2, Plus, Repeat, Sparkles, Timer, Trash2, X,
} from 'lucide-react';
import { useTodo } from '../../context/TodoContext';
import { useToast } from '../../context/ToastContext';
import { PRIORITIES, PRIORITY_META, RECURRENCE_LABELS, STATUSES, STATUS_META } from '../../lib/taskModel';
import { formatDuration, toDate } from '../../lib/date';
import { suggestSubtasks } from '../../lib/ai';
import { cn } from '../../lib/cn';
import { Modal } from '../ui/Modal';
import { Button, IconButton } from '../ui/Button';
import { Input, Select, Textarea } from '../ui/Input';
import { TaskCheckbox } from './TaskCheckbox';
import { Progress } from '../ui/primitives';

/** `<input type="datetime-local">` wants a local-time string, not an ISO one. */
const toLocalInput = (value) => {
  const date = toDate(value);
  if (!date) return '';
  return format(date, "yyyy-MM-dd'T'HH:mm");
};

/**
 * Full task editor.
 *
 * The previous UI had no way to change a task at all after creation — no
 * rename, no due date, no priority, no notes. Everything editable now lives
 * here, and every field saves on change.
 */
export function TaskDetail({ task, open, onClose }) {
  return (
    <Modal open={open && Boolean(task)} onClose={onClose} size="lg" className="max-h-[82vh] overflow-hidden">
      {/* Keying by task id resets every draft field when a different task is
          opened, which is React's own answer to "reset state when a prop
          changes" — no synchronising effect required. */}
      {task && <TaskDetailBody key={task.id} task={task} onClose={onClose} />}
    </Modal>
  );
}

function TaskDetailBody({ task, onClose }) {
  const { updateTask, deleteTask, addSubtask, toggleSubtask, removeSubtask } = useTodo();
  const toast = useToast();

  const [title, setTitle] = useState(task.title);
  const [notes, setNotes] = useState(task.notes ?? '');
  const [newSubtask, setNewSubtask] = useState('');
  const [generating, setGenerating] = useState(false);

  // While a field is untouched, follow changes arriving from another device
  // rather than holding a stale draft that would overwrite them on blur.
  // Adjusting state during render is React's documented answer to "derive from
  // props without an effect"; it re-renders before the browser paints.
  const [remote, setRemote] = useState({ title: task.title, notes: task.notes ?? '' });
  const [dirty, setDirty] = useState({ title: false, notes: false });

  if (remote.title !== task.title || remote.notes !== (task.notes ?? '')) {
    setRemote({ title: task.title, notes: task.notes ?? '' });
    if (!dirty.title) setTitle(task.title);
    if (!dirty.notes) setNotes(task.notes ?? '');
  }

  const subtasks = task.subtasks ?? [];
  const doneCount = subtasks.filter((subtask) => subtask.completed).length;
  const tagText = useMemo(() => (task.tags ?? []).join(', '), [task.tags]);

  const save = (patch) => updateTask(task.id, patch);

  const commitTitle = () => {
    const next = title.trim();
    if (next && next !== task.title) save({ title: next });
    else if (!next) setTitle(task.title);
    setDirty((current) => ({ ...current, title: false }));
  };

  const commitTags = (value) => {
    const tags = [
      ...new Set(
        value
          .split(',')
          .map((tag) => tag.trim().toLowerCase().replace(/^#/, ''))
          .filter(Boolean),
      ),
    ];
    save({ tags });
  };

  const handleGenerateSubtasks = async () => {
    setGenerating(true);
    const { items, source } = await suggestSubtasks(task.title);
    setGenerating(false);

    if (!items.length) {
      toast.info('No breakdown suggestions for this one', {
        description: 'Try a more descriptive title, like "Prepare the Q3 review deck".',
      });
      return;
    }

    const existing = new Set(subtasks.map((subtask) => subtask.title.toLowerCase()));
    const additions = items
      .filter((item) => !existing.has(item.toLowerCase()))
      .map((item, index) => ({
        id: `sub-${Date.now()}-${index}`,
        title: item,
        completed: false,
      }));

    if (!additions.length) {
      toast.info('Those steps are already on this task');
      return;
    }

    save({ subtasks: [...subtasks, ...additions] });
    toast.success(`Added ${additions.length} steps`, {
      description: source === 'ai' ? 'Generated by AI' : 'From the built-in playbook',
    });
  };

  return (
    <div className="flex max-h-[82vh] flex-col">
      {/* Header */}
      <div className="flex items-start gap-3 border-b border-line px-5 py-4">
        <TaskCheckbox
          checked={task.completed}
          onChange={() => save({ completed: !task.completed, completedAt: task.completed ? null : new Date() })}
          title={task.title}
          className="mt-1.5"
        />
        <input
          value={title}
          onChange={(event) => setTitle(event.target.value)}
          onBlur={commitTitle}
          onKeyDown={(event) => event.key === 'Enter' && event.currentTarget.blur()}
          aria-label="Task title"
          className={cn(
            'min-w-0 flex-1 rounded-md bg-transparent px-1 py-1 text-lg font-semibold text-ink outline-none',
            'hover:bg-surface-sunken focus:bg-surface-sunken',
            task.completed && 'text-ink-muted line-through',
          )}
        />
        <IconButton label="Close" size="sm" onClick={onClose}>
          <X className="h-4 w-4" />
        </IconButton>
      </div>

      <div className="min-h-0 flex-1 space-y-5 overflow-y-auto px-5 py-5 scrollbar-thin">
        {/* Scheduling and classification */}
        <div className="grid gap-4 sm:grid-cols-2">
          <Input
            type="datetime-local"
            label="Due"
            value={toLocalInput(task.dueDate)}
            onChange={(event) =>
              save({
                dueDate: event.target.value ? new Date(event.target.value) : null,
                hasTime: Boolean(event.target.value),
              })
            }
            leadingIcon={<CalendarDays className="h-4 w-4" />}
          />

          <Select
            label="Priority"
            value={task.priority}
            onChange={(event) => save({ priority: event.target.value })}
          >
            {PRIORITIES.map((priority) => (
              <option key={priority} value={priority}>
                {PRIORITY_META[priority].label}
              </option>
            ))}
          </Select>

          <Select
            label="Column"
            value={task.status}
            onChange={(event) => {
              const status = event.target.value;
              save({
                status,
                completed: status === 'done',
                completedAt: status === 'done' ? (task.completedAt ?? new Date()) : null,
              });
            }}
          >
            {STATUSES.map((status) => (
              <option key={status} value={status}>
                {STATUS_META[status].label}
              </option>
            ))}
          </Select>

          <Select
            label="Repeat"
            value={task.recurrence ?? ''}
            onChange={(event) => save({ recurrence: event.target.value || null })}
          >
            <option value="">Does not repeat</option>
            {Object.entries(RECURRENCE_LABELS).map(([rule, label]) => (
              <option key={rule} value={rule}>
                {label}
              </option>
            ))}
          </Select>

          <Input
            label="Tags"
            defaultValue={tagText}
            key={`tags-${task.id}-${tagText}`}
            placeholder="work, urgent"
            onBlur={(event) => commitTags(event.target.value)}
            leadingIcon={<Hash className="h-4 w-4" />}
            hint="Comma separated"
          />

          <Input
            label="Estimate"
            type="number"
            min={0}
            step={5}
            defaultValue={task.estimateMinutes ?? ''}
            key={`estimate-${task.id}-${task.estimateMinutes}`}
            placeholder="Minutes"
            onBlur={(event) =>
              save({ estimateMinutes: event.target.value ? Number(event.target.value) : null })
            }
            leadingIcon={<Timer className="h-4 w-4" />}
            hint={task.estimateMinutes ? formatDuration(task.estimateMinutes) : 'How long will this take?'}
          />
        </div>

        <Textarea
          label="Notes"
          value={notes}
          rows={4}
          placeholder="Context, links, anything you need when you pick this up again."
          onChange={(event) => setNotes(event.target.value)}
          onBlur={() => notes !== (task.notes ?? '') && save({ notes })}
        />

        {/* Subtasks */}
        <section className="space-y-3">
          <div className="flex items-center justify-between gap-3">
            <h3 className="text-sm font-semibold text-ink">
              Steps{' '}
              {subtasks.length > 0 && (
                <span className="font-normal text-ink-muted">
                  {doneCount}/{subtasks.length}
                </span>
              )}
            </h3>
            <Button size="xs" variant="secondary" onClick={handleGenerateSubtasks} disabled={generating}>
              {generating ? (
                <Loader2 className="h-3.5 w-3.5 animate-spin" />
              ) : (
                <Sparkles className="h-3.5 w-3.5 text-accent-500" />
              )}
              Suggest steps
            </Button>
          </div>

          {subtasks.length > 0 && (
            <Progress
              value={doneCount}
              max={subtasks.length}
              label={`${doneCount} of ${subtasks.length} steps complete`}
              barClassName="bg-emerald-500"
            />
          )}

          <ul className="space-y-1">
            {subtasks.map((subtask) => (
              <li key={subtask.id} className="group flex items-center gap-2.5 rounded-lg px-1 py-1.5 hover:bg-surface-sunken">
                <TaskCheckbox
                  size="sm"
                  checked={subtask.completed}
                  onChange={() => toggleSubtask(task.id, subtask.id)}
                  title={subtask.title}
                />
                <span className={cn('min-w-0 flex-1 text-sm text-ink', subtask.completed && 'text-ink-muted line-through')}>
                  {subtask.title}
                </span>
                <IconButton
                  label={`Remove step "${subtask.title}"`}
                  size="xs"
                  variant="danger-ghost"
                  className="opacity-0 transition-opacity focus-visible:opacity-100 group-hover:opacity-100"
                  onClick={() => removeSubtask(task.id, subtask.id)}
                >
                  <Trash2 className="h-3.5 w-3.5" />
                </IconButton>
              </li>
            ))}
          </ul>

          <form
            onSubmit={(event) => {
              event.preventDefault();
              addSubtask(task.id, newSubtask);
              setNewSubtask('');
            }}
            className="flex items-center gap-2 rounded-lg border border-dashed border-line px-3 py-2"
          >
            <Plus className="h-4 w-4 flex-shrink-0 text-ink-subtle" aria-hidden="true" />
            <input
              value={newSubtask}
              onChange={(event) => setNewSubtask(event.target.value)}
              placeholder="Add a step"
              aria-label="New step"
              className="min-w-0 flex-1 bg-transparent text-sm text-ink outline-none placeholder:text-ink-subtle"
            />
            {newSubtask.trim() && (
              <Button type="submit" size="xs" variant="primary">
                Add
              </Button>
            )}
          </form>
        </section>

        {/* Provenance */}
        <dl className="grid grid-cols-2 gap-3 border-t border-line pt-4 text-xs text-ink-subtle">
          <div>
            <dt className="font-medium text-ink-muted">Created</dt>
            <dd>{task.createdAt ? format(task.createdAt, "d MMM yyyy 'at' HH:mm") : '—'}</dd>
          </div>
          <div>
            <dt className="font-medium text-ink-muted">Completed</dt>
            <dd>{task.completedAt ? format(task.completedAt, "d MMM yyyy 'at' HH:mm") : '—'}</dd>
          </div>
        </dl>
      </div>

      <div className="flex items-center justify-between gap-3 border-t border-line px-5 py-3">
        <Button
          variant="danger-ghost"
          size="sm"
          onClick={() => {
            deleteTask(task.id);
            onClose();
          }}
        >
          <Trash2 className="h-4 w-4" />
          Delete task
        </Button>
        <div className="flex items-center gap-2">
          {task.recurrence && (
            <span className="inline-flex items-center gap-1 text-xs text-ink-muted">
              <Repeat className="h-3 w-3" />
              {RECURRENCE_LABELS[task.recurrence]}
            </span>
          )}
          <Button variant="primary" size="sm" onClick={onClose}>
            Done
          </Button>
        </div>
      </div>
    </div>
  );
}
