import { useMemo, useState } from 'react';
import { AnimatePresence, motion } from 'framer-motion';
import { AlertTriangle, Brain, Lightbulb, Sparkles, X } from 'lucide-react';
import { useTodo } from '../context/TodoContext';
import { localInsights, suggestCoaching, suggestSubtasks } from '../lib/ai';
import { summarise } from '../lib/analytics';
import { useAsyncResource } from '../hooks/useAsyncResource';
import { useLocalStorage } from '../hooks/useLocalStorage';
import { useToast } from '../context/ToastContext';
import { cn } from '../lib/cn';
import { Button } from './ui/Button';

const SEVERITY = {
  high: {
    wrap: 'border-rose-200 bg-rose-50 dark:border-rose-900 dark:bg-rose-950/40',
    icon: 'bg-rose-100 text-rose-600 dark:bg-rose-900/60 dark:text-rose-300',
    Icon: AlertTriangle,
  },
  medium: {
    wrap: 'border-amber-200 bg-amber-50 dark:border-amber-900 dark:bg-amber-950/40',
    icon: 'bg-amber-100 text-amber-600 dark:bg-amber-900/60 dark:text-amber-300',
    Icon: Lightbulb,
  },
  low: {
    wrap: 'border-line bg-surface',
    icon: 'bg-surface-sunken text-ink-muted',
    Icon: Sparkles,
  },
};

/**
 * Workload insights.
 *
 * Dismissals are keyed by a stable insight `id` and persisted, so an insight
 * you have waved away does not reappear on every render — the previous version
 * keyed dismissals off the message text, which changed as the counts changed.
 */
export function CoachPanel({ onOpenTask }) {
  const { tasks, updateTask } = useTodo();
  const toast = useToast();
  const [dismissed, setDismissed] = useLocalStorage('action.dismissedInsights', []);
  const [busyId, setBusyId] = useState(null);
  const [expanded, setExpanded] = useState(false);

  const stats = useMemo(() => summarise(tasks), [tasks]);

  const { data: coaching } = useAsyncResource(
    async ({ signal }) => (await suggestCoaching(stats, { signal })).value,
    // Re-ask only when the numbers that matter actually move.
    [stats.open, stats.overdue, stats.completedToday, stats.streak],
    { enabled: tasks.length > 0 },
  );

  // Cap what is shown. More than a couple of advisory cards pushes the actual
  // task list below the fold, which defeats the point of the screen.
  const MAX_VISIBLE = 2;
  const allInsights = useMemo(
    () => localInsights(tasks).filter((insight) => !dismissed.includes(insight.id)),
    [tasks, dismissed],
  );
  const insights = expanded ? allInsights : allInsights.slice(0, MAX_VISIBLE);

  const dismiss = (id) => setDismissed((current) => [...new Set([...current, id])]);

  const handleBreakdown = async (insight) => {
    setBusyId(insight.id);
    const { items, source } = await suggestSubtasks(insight.task.title);
    setBusyId(null);

    if (!items.length) {
      toast.info('No breakdown available for that one');
      return;
    }

    updateTask(insight.task.id, {
      subtasks: items.map((title, index) => ({
        id: `sub-${Date.now()}-${index}`,
        title,
        completed: false,
      })),
    });
    dismiss(insight.id);
    toast.success(`Added ${items.length} steps`, {
      description: source === 'ai' ? 'Generated by AI' : 'From the built-in playbook',
    });
  };

  const handleRescheduleOverdue = (insight) => {
    const today = new Date();
    today.setHours(9, 0, 0, 0);
    insight.tasks.forEach((task) => updateTask(task.id, { dueDate: today }));
    dismiss(insight.id);
    toast.success(`Moved ${insight.tasks.length} tasks to today`);
  };

  if (!coaching && allInsights.length === 0) return null;

  return (
    <section aria-label="Productivity insights" className="space-y-2">
      {coaching && (
        <p className="flex items-center gap-2 px-1 text-sm text-ink-muted">
          <Brain className="h-3.5 w-3.5 flex-shrink-0 text-brand-600 dark:text-brand-400" aria-hidden="true" />
          {coaching}
        </p>
      )}

      <AnimatePresence initial={false}>
        {insights.map((insight) => {
          const style = SEVERITY[insight.severity] ?? SEVERITY.low;
          return (
            <motion.div
              key={insight.id}
              layout
              initial={{ opacity: 0, y: -6 }}
              animate={{ opacity: 1, y: 0 }}
              exit={{ opacity: 0, x: -24, transition: { duration: 0.15 } }}
              className={cn('flex items-start gap-2.5 rounded-xl border px-3.5 py-2.5', style.wrap)}
            >
              <span className={cn('mt-0.5 flex h-6 w-6 flex-shrink-0 items-center justify-center rounded-md', style.icon)}>
                <style.Icon className="h-3.5 w-3.5" aria-hidden="true" />
              </span>

              <div className="min-w-0 flex-1">
                <p className="text-sm font-medium text-ink">{insight.title}</p>
                <p className="mt-0.5 text-xs text-ink-muted">{insight.body}</p>

                {insight.tasks && (
                  <ul className="mt-1.5 flex flex-wrap gap-x-2 gap-y-0.5">
                    {insight.tasks.map((task) => (
                      <li key={task.id}>
                        <button
                          type="button"
                          onClick={() => onOpenTask?.(task.id)}
                          className="max-w-[14rem] truncate rounded bg-black/5 px-1.5 py-0.5 text-xs text-ink-muted hover:text-ink dark:bg-white/10"
                        >
                          {task.title}
                        </button>
                      </li>
                    ))}
                  </ul>
                )}

                {insight.action === 'breakdown' && (
                  <Button
                    size="xs"
                    variant="primary"
                    className="mt-2"
                    loading={busyId === insight.id}
                    onClick={() => handleBreakdown(insight)}
                  >
                    <Sparkles className="h-3.5 w-3.5" />
                    Break it into steps
                  </Button>
                )}

                {insight.action === 'reschedule-overdue' && (
                  <Button size="xs" variant="secondary" className="mt-2" onClick={() => handleRescheduleOverdue(insight)}>
                    Move them to today
                  </Button>
                )}
              </div>

              <button
                type="button"
                onClick={() => dismiss(insight.id)}
                aria-label={`Dismiss: ${insight.title}`}
                className="rounded-md p-1 text-ink-subtle transition-colors hover:bg-black/5 hover:text-ink dark:hover:bg-white/10"
              >
                <X className="h-4 w-4" />
              </button>
            </motion.div>
          );
        })}
      </AnimatePresence>

      {allInsights.length > MAX_VISIBLE && (
        <button
          type="button"
          onClick={() => setExpanded((current) => !current)}
          className="px-1 text-xs font-medium text-ink-muted hover:text-ink"
        >
          {expanded
            ? 'Show fewer insights'
            : `Show ${allInsights.length - MAX_VISIBLE} more insight${allInsights.length - MAX_VISIBLE > 1 ? 's' : ''}`}
        </button>
      )}
    </section>
  );
}
